name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pyqt5
        pip install pyyaml
        pip install xmltodict

    - name: Build executable
      run: pyinstaller --onefile main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DataConversionProject-windows
        path: dist/main.exe
